### PR TITLE
Add editorconfig

### PR DESCRIPTION
**Pull request by moshe**

### CODE REVIEW

**Comment by BenjaminProgram** [comment]
This would be a helpful addition.

**Comment by phildini** [comment]
I guess I'm not certain it's necessary for the purpose of this repo? I'm willing to be convinced otherwise.

**Comment by BenjaminProgram** [comment]
It is not necessary but could be helpful to some.

**Comment by MosheZada** [comment]
Adding editorconfig will make pull requests flow more easily.
Writing the code, fixing it in the IDE, and send the pull request to review, 
No wait for travis and no newline or space related build failure, all resolved in the IDE. 
I pretty sure most of people in readme repos not familiar with doc8 so they suggest their pull request and forget about it - causing old-unmerged pull request that will never~ be fixed.

**Comment by HybridDog** [comment]
as far as l know, in markdown files you usually use trailing whitespaces for line break

**Pull request closed without merging**
