### PR TITLE
explanation about mandatory connection header

### PR DESCRIPTION
**Pull request by dhaowoods**
HTTP/1.1 applications that do not support persistent connections MUST include the "close" connection option in every message.

### CODE REVIEW

**Comment by phildini** [comment]
I think you want to apply these changes to master, maybe? You seem to have applied to a branch.

**Comment by dhaowoods** [comment]
yah, but I thougth I have no permission to apply these changes to master, have I?

**Comment by aprescott** [comment]
You can't edit the `master` branch of this project without your account set as a contributor, but you can set a pull request to be merged into `master`. You just can't merge it as a non-contributor.

**Comment by phildini** [comment]
What @aprescott said. Right now you're proposing to merge your changes into a branch; I'm suggesting you redo your changes to merge onto master and re-do the PR.

**Comment by dhaowoods** [comment]
okay.. thank you :-D

**Pull request closed without merging**
