### PR TITLE
DNS section - corrections and more detail

### PR DESCRIPTION
**Pull request by bbhart**
Made corrections, reverted part where it became *NIX specific, added detail.

### CODE REVIEW

**Comment by dtracers** [comment]
Dont forget that about what #62 is writing.  :)

**Comment by phildini** [comment]
Would you remind reviewing the test failures and fixing the associated problems? https://travis-ci.org/alex/what-happens-when/builds/47395236

**Comment by bbhart** [comment]
Done!

**Comment by phildini** [comment]
Thanks for being so quick! Unfortunately, HEAD on master has marched on. Would you mind resolving the conflict?

**Comment by phildini** [comment]
Hello! Thanks for taking the time to update the DNS section. In an ideal world, yourself and the author of #62  would collaborate, look at what's currently in the DNS section, and agree on the best path forward. 

Thanks again!

**Comment by bbhart** [comment]
Understood. It's probably not something I'll have bandwidth for until late this week, unfortunately.




Cheers.

**Comment by holms** [comment]
Can this PLEASE be resolved? THere's almost nothing about DNS in the document, a most common part on interview, about it's cache, and root server name resolving.

**Comment by phildini** [comment]
Unfortunately I don't have the bandwidth to resolve the conflict, and I'm not sure @bbhart does either. @holms, feel free to try and take the current PRs about DNS and pull them into something reasonable on top of current master.

Thanks!

**Pull request closed without merging**
