### PR TITLE
Added a reference to Google's custom web server

### PR DESCRIPTION
**Pull request by adsouza**

### CODE REVIEW

**Comment by ChipWolf** [comment]
It's called 'GWS (Google Web Server)' not 'a bespoke one'

**Comment by adsouza** [comment]
Edited my branch to reflect that.

**Comment by ChipWolf** [comment]
You did? You didn't update patch-1, which is the branch you used for this PR ;)

**Comment by ChipWolf** [comment]
Might want to re-open this pull request off your patch-1 branch.
Looks like this PR isn't tracking your latest change

**Comment by adsouza** [comment]
Sorry, I'm not that familiar with Git & it's not very clear how to do this...

**Comment by HybridDog** [comment]
http://marklodato.github.io/visual-git-guide/index-en.html

**Comment by adsouza** [comment]
Wow, that sounds more complicated than you just copying my 1 line change ;-p

**Pull request closed without merging**
